import os
import subprocess
import requests
import shutil
import time
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
if not GITHUB_TOKEN:
    print("Error: GITHUB_TOKEN environment variable not set.")
    exit(1)
GITHUB_USERNAME = "jadoholmes"
FOLDER_TO_DEPLOY = "output_site/phase2_frontend"  # Folder generated by your main script
REPO_PREFIX = "website-auto-"
BRANCH_NAME = "gh-pages"

frontend_path = os.path.abspath(FOLDER_TO_DEPLOY)

# Delete previous .html/.css/.js files from root before copying new ones
for file in os.listdir():
    if file.endswith((".html", ".css", ".js")):
        os.remove(file)

# Step 1: Create a unique repo name
timestamp = int(time.time())
REPO_NAME = f"{REPO_PREFIX}{timestamp}"
LIVE_URL = f"https://{GITHUB_USERNAME}.github.io/{REPO_NAME}/"

# Step 2: Create repo on GitHub
print(f" Creating repo {REPO_NAME}...")
res = requests.post(
    "https://api.github.com/user/repos",
    auth=(GITHUB_USERNAME, GITHUB_TOKEN),
    json={"name": REPO_NAME, "auto_init": False, "private": False}
)

if res.status_code != 201:
    print(" Failed to create repo:", res.text)
    exit(1)
print(" Repo created.")

# Step 3: Create local Git repo inside the folder
print(" Setting up local Git repo...")
orig_dir = os.getcwd()

source_dir = os.path.abspath(FOLDER_TO_DEPLOY)
dest_dir = orig_dir

import shutil
import time

# Clean old HTML/CSS/JS files from root (dest_dir) before copying
for file in os.listdir(dest_dir):
    if file.endswith((".html", ".css", ".js")):
        try:
            os.remove(os.path.join(dest_dir, file))
        except Exception as e:
            print(f"Warning: Could not remove {file}: {e}")

# Copy all files/folders from source_dir (phase2_frontend) to root dest_dir
for item in os.listdir(source_dir):
    s = os.path.join(source_dir, item)
    d = os.path.join(dest_dir, item)

    # Remove existing files/folders at destination
    if os.path.exists(d):
        if os.path.isfile(d) or os.path.islink(d):
            os.remove(d)
        else:
            shutil.rmtree(d)

    # Copy file or folder
    if os.path.isdir(s):
        shutil.copytree(s, d)
    else:
        shutil.copy2(s, d)

# Change directory back to root for git commands
os.chdir(dest_dir)

# 🔧 Remove submodule leftovers inside phase2_frontend (this is what's causing the issue)
import stat

def force_remove_readonly(func, path, excinfo):
    os.chmod(path, stat.S_IWRITE)
    func(path)

frontend_git_dir = os.path.join(frontend_path, '.git')
if os.path.exists(frontend_git_dir):
    shutil.rmtree(frontend_git_dir, onerror=force_remove_readonly)


# Optional: also remove old .gitmodules just in case
if os.path.exists(".gitmodules"):
    os.remove(".gitmodules")

# Re-init Git clean
shutil.rmtree(".git", ignore_errors=True)
subprocess.run(["git", "init"], check=True)


#  Submodule cleanup (to fix gh-pages deployment failure)
if os.path.exists(".gitmodules"):
    os.remove(".gitmodules")
subprocess.run(["git", "rm", "--cached", "phase2_frontend"], check=False)
shutil.rmtree(".git", ignore_errors=True)  # delete old git data if any

subprocess.run(["git", "init"], check=True)
# Try switching to the branch, create if it doesn't exist
branches = subprocess.run(["git", "branch"], capture_output=True, text=True).stdout.splitlines()
branches = [b.strip().lstrip('* ') for b in branches]

if BRANCH_NAME not in branches:
    subprocess.run(["git", "checkout", "-b", BRANCH_NAME], check=True)
else:
    subprocess.run(["git", "checkout", BRANCH_NAME], check=True)

subprocess.run(["git", "add", "."], check=True)

result = subprocess.run(["git", "status", "--porcelain"], capture_output=True, text=True)
if result.stdout.strip():
    subprocess.run(["git", "commit", "-m", "Initial site deploy"], check=True)
else:
    print("No changes to commit.")


# Step 4: Push to GitHub
remote_url = f"https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git"
remotes = subprocess.run(["git", "remote"], capture_output=True, text=True).stdout.splitlines()
if "origin" not in remotes:
    subprocess.run(["git", "remote", "add", "origin", remote_url], check=True)
else:
    subprocess.run(["git", "remote", "set-url", "origin", remote_url], check=True)

subprocess.run(["git", "push", "-u", "origin", BRANCH_NAME, "--force"], check=True)


index_html_path = os.path.join(dest_dir, "index.html")
error_page_path = os.path.join(dest_dir, "404.html")

if os.path.exists(index_html_path):
    shutil.copy(index_html_path, error_page_path)
    print(" 404.html created as a copy of index.html to fix React routing.")
else:
    print(" Error: index.html not found — can't create 404.html.")
# Step 5: Enable GitHub Pages on gh-pages branch
# Wait a few seconds so GitHub processes your repo and branch
print(" Waiting for GitHub to process the repo before enabling Pages...")
time.sleep(5)

print(" Enabling GitHub Pages...")
pages_res = requests.post(
    f"https://api.github.com/repos/{GITHUB_USERNAME}/{REPO_NAME}/pages",
    headers={"Authorization": f"Bearer {GITHUB_TOKEN}"},
    json={
        "source": {
            "branch": BRANCH_NAME,
            "path": "/"
        }
    }
)

if pages_res.status_code not in [201, 204]:
    print(" GitHub Pages setup may have failed:", pages_res.text)
else:
    print(f" GitHub Pages enabled.")

print(f"\n Your site is now live at:\n{LIVE_URL}")
